### ISSUE TITLE
Favorites lost

### ISSUE THREAD

**Issue by angomania** [BuXXe/movian-bs-plugin#1] opened 2016-01-19 15:01 UTC
If I add favorites, it could happens that they are gone after a restart of movian.

**Comment by BuXXe** [comment] 2016-01-19 15:09
Yeah, I encountered the very same thing yesterday. Already tried to nail down the reason but could not yet find any. One of those problems where reproducability is the hardest thing. Have you any hint on how it happened?

**Comment by angomania** [comment] 2016-01-19 15:49
Unfortunately not. It happens irregularly. Sometimes the list is empty when I restart the PS3, sometimes when I restart movian or sometimes between playing games.
That's a shame, because it is my favorite plugin ;)

**Comment by BuXXe** [comment] 2016-01-20 12:36
Ok, In short: I got the problem :D and I will fix it for next release. Until then, just try to not favorite series with Umlaut in their title :D.
For the technical interested:
After some hours of trying to reproduce the problem (cause it really did not happen each time) I came to this situation:
The code for createstore is called and then the check for store.favorites existence is done. This existence check failed and therefor generated a new list store.favorites = "[]";.
The reason for this was, after some try catching, that the JSON seemed to get corrupted and missed some ending: ]"}
Funny thing here: the number of missing closing symbols varied. sometimes only the } was missing.
And now on to the reason:
When the user tries to add an entry with an Umlaut like Flöte, the json encoding created FlÃ–te. And heres the problem:
The ö is converted to 2 characters Ã–. If we have more Umlauts, the problem gets even worse and we have multiple 1 to 2 character conversion. 
This results in a problem for the write back to file call for the storage file (it seems).
For me it seems that the write back call uses the original length of the string 
for example: {"favorites":"[{"test":"flöte"}]"}
but will write back
{"favorites":"[{"test":"flÃ–te"}]"
-> see the missing }

I dont know if this is something the plugin developer should take care of or if the JSON Encoding / write back call needs some fix. One thing is for sure: That was a tough one to nail down -.-.

**Comment by angomania** [comment] 2016-01-20 14:17
Nice. Good job :)

**Comment by BuXXe** [comment] 2016-01-20 14:29
Uploaded the new release just now. Waiting for approval. Should be online soon. Otherwise you can directly take the release from the github release folder. I also added titles for episode, season and host for episodes pages.

**Closed as completed by BuXXe** 2016-01-20 14:29 UTC

**Comment by ghost** [comment] 2016-02-19 03:07
Are you planing to develope a cine.to Plugin?

Btw. Thanks for releasing your plugins

Planst du auch ein Cine.to Plugin zu entwickeln?

Wäre mega und danke für deine bisherigen Plugins

**Comment by BuXXe** [comment] 2016-02-20 18:42
Thank you for the flowers, but I dont plan to develop a cine.to plugin.
I just did it without planning :P.

Have a look at it here: https://github.com/BuXXe/movian-cine-plugin
I will request a release on the movian plugins site today but it takes some time for approval so if you wanna test it, just download the .zip file from the Release/0.1 folder.

Due to the limited GUI capabilities I had to reduce the filter functionalities of the web page to a minimum in order to keep it easy to use. Furthermore, I just wrote the plugin down and didnt invest much time testing so if you encounter problems or have a feature request, just post an issue.

**Comment by ghost** [comment] 2016-02-20 22:58
Great Work, i' ll test it :+1:

**Comment by angomania** [comment] 2016-02-21 08:10
Thanx for the new plugin.

**Comment by ghost** [comment] 2016-03-01 10:47
Thanks man, it works great like every of your plugins. Love your work

**Comment by angomania** [comment] 2016-03-01 15:18
Love your plugins, using it also on windows chrome/iron movian app. 
Your plugins are not listed in this version, but I have successfully added them with a trick ;)

Could you make your plugins working for kodi mediaplayer?
I´d like to have them all on my raspberry pie :)

**Comment by BuXXe** [comment] 2016-03-01 16:57
yeah i know about the chrome app which does not yet list all plugins but as you said, there is a way to make them work. 

On the kodi mediaplayer thing: 
I dont think I will do a kodi port cause of several reasons:
1. its a completely different architecture (they use python for their add-ons afaik and movian is JS).
Although I code Python regularly I just dont want to have the overhead of writing the same plugin in 2 languages and then trying to keep them somehow similar.
2. I run movian on my PS3 and dont want to set up a Rpi media center just to create the right environment to test the add-ons. 

So, sorry but you have to take what you get :)

**Comment by Chris777777** [comment] 2016-03-12 02:29
Hi ich hoffe mal das du Deutsch kannst :) Ich habe das Plugin auf meiner Ps3 installiert, also über Movain.Aber das Plugin wird nicht im Home Menu angezeigt :/ Kannst du mir erklären was ich falsch gemacht habe? Danke das du wenigstens das rausgebracht hast :)

**Comment by Chris777777** [comment] 2016-03-12 02:33
Thanks for the great plugin :)But why does not work on the Ps3?

**Comment by angomania** [comment] 2016-03-12 13:49
Auf meiner PS3  mit CFW Rebug, laufen die Plugins. In Webman (wo showtime/movian integriert ist) als auch im Standalone Movian (https://movian.tv/downloads/movian). 
Schau mal per FTP nach, ob die heruntergeladenen Plugins im folgenden Verzeichnis zu sehen sind:
"/dev_hdd0/game/HTSS00003/USRDIR/settings/installedplugins" dort liegen die Plugins als .zip Files.

**Comment by BuXXe** [comment] 2016-03-12 21:34
I will stick to english so that if there will be someone having the same problem(s), I / we don't have to elaborate this again.
First off: I am testing my stuff solely on the PS3 (CFW Rebug). 
@angomania: Just to clarify this one: I guess you have mistaken this. Webman is the tool integrated in the XMB of the PS3. It gives you the ability to mount games / use the PS3MAPI and the integrated FTP server (stuff like that). It is called Webman(ager) cause its GUI is based on websites / a webserver. 
Movian (formerly known as showtime) is integrated in Multiman, a standalone manager application with similar features like webman. At least this is the configuration I know and use. 
I dont think there is any integration of showtime / movian in webman.
On to the real question:
- I need some more info: CFW Version, How do you use Movian? (Integrated into Multiman?) Which Multiman Version and which Movian Version do you use?
- for faster debugging: please send me your logfile. You can access the logfiles via the webinterface of movian: open the following url in browser: your PS3-IP:42000 while movian is running. There you see links to the logfiles.

If you want to nail this one down faster, we could contact each other via instant messaging like skype

**Comment by angomania** [comment] 2016-03-13 07:32
Yes my fault, I mean Multiman.
